version: "3.5"
services:
  api:
    image: mkozi/gbe_api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "9000:9000"
  client:
    image: mkozi/gbe_client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - /app/node_modules
      - ./client:/app
    ports:
      - "3050:3000"
      - "35729:35729"
    

